name: codictionary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  http: ^1.1.0
  path_provider: ^2.0.17
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  uuid: ^4.4.0
  reorderable_grid_view: ^2.2.8
  reorderable_grid: ^1.0.12
  msix: ^3.16.12
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1

msix_config:
  display_name: Codictionary
  publisher_display_name: Sergey Ivanov
  identity_name: com.sergey.codictionary
  logo_path: windows\\runner\\resources\\app_icon.ico
  start_menu: true
  shortcut: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  windows:
    generate: true
  image_path: "assets/media/ffc2b8b3-e3ac-4cac-8e3a-1b6915d3630f.png"

flutter:
  uses-material-design: true
  fonts:
    - family: CodictionaryCartoon
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
  assets:
    - .env
    - assets/dictionary.json
    - assets/media/
    - assets/media/icons/
    - assets/media/icons/new_dictionary/
